store_homepage:
    path: /
    defaults: { _controller: StoreBundle:Index:index }

store_login:
    path: /login
    defaults: { _controller: StoreBundle:Security:login }

user_registration:
    path: /register
    defaults: { _controller: StoreBundle:Registration:register }

cart:
    path: /cart
    defaults: { _controller: StoreBundle:Cart:cart }

store_stores_loc:
    path: /stores
    defaults: { _controller: StoreBundle:Stores:stores }

store_user:
    path: /user/{id}
    defaults: { _controller: StoreBundle:User:index }

category:
    path: /{title}
    defaults: { _controller: StoreBundle:Category:category }

admin_login:
    path: /admin
    defaults: { _controller: StoreBundle:Security:adminLogin }

user_logout:
    path: /logout

store_changeLang:
    path: /changelang
    defaults: { _controller: StoreBundle:Main:changeLang }

admin_control_panel:
    path: /admin/cpanel
    defaults: { _controller: StoreBundle:Admin:cpanel}

admin_registration:
    path: /regadmin
    defaults: { _controller: StoreBundle:Registration:regAdmin }

admin_logout:
    path: /admin/cpanel/logout

currency:
    path: /admin/cpanel/currency
    defaults: { _controller: StoreBundle:Admin:settingsCurrency }

lang:
    path: /admin/cpanel/lang
    defaults: { _controller: StoreBundle:Admin:settingsLang }

locale:
    path: /admin/cpanel/locale
    defaults: { _controller: StoreBundle:Admin:settingsLocale }

categories:
    path: /admin/cpanel/categories
    defaults: { _controller: StoreBundle:Admin:settingsCategories }

add_new_currency:
    path: /admin/cpanel/addnewcurrency
    defaults: { _controller: StoreBundle:Admin:addNewCurrency }

delete_currency:
    path: /admin/cpanel/deletecurrency
    defaults: { _controller: StoreBundle:Admin:deleteCurrency }

update_currency:
    path: admin/cpanel/updatecurrency
    defaults: { _controller: StoreBundle:Admin:updateCurrency }


get_transl_by_page:
    path: /admin/cpanel/langbypage
    defaults: { _controller: StoreBundle:Admin:getTranslateByPage }

show_translations:
    path: /admin/cpanel/translations/{id}
    defaults: { _controller: StoreBundle:Admin:showTranslations }

add_keyword:
    path: /admin/cpanel/addkeyword
    defaults: { _controller: StoreBundle:Admin:addKeyword }

add_translate:
    path: /admin/cpanel/addtranslate
    defaults: { _controller: StoreBundle:Admin:addTranslations }

single_row_update:
    path: /admin/cpanel/singlerowupdate
    defaults: { _controller: StoreBundle:Admin:singleRowSave }

save_all:
    path: /admin/cpanel/saveall
    defaults: { _controller: StoreBundle:Admin:saveAll }

delete_keyword:
    path: /admin/cpanel/deletekeyword
    defaults: { _controller: StoreBundle:Admin:deleteKeyword }

render_category:
    path: /admin/service/renderCaregory
    defaults: { _controller: StoreBundle:Category:renderCategoryList }