store_homepage:
    path:     /{lang}
    defaults: { _controller: StoreBundle:Default:index, lang: en}
    requirements:
            lang: en|pl|ru

store_login:
    path: /login
    defaults: { _controller: StoreBundle:Security:login }

store_admin:
    path: /admin
    defaults: { _controller: StoreBundle:Admin:index }

user_registration:
    path:     /register
    defaults: { _controller: StoreBundle:Registration:register }

store_logout:
    path: /logout