store_homepage:
    path:     /
    defaults: { _controller: StoreBundle:Main:index }

store_login:
    path: /login
    defaults: { _controller: StoreBundle:Security:login }

store_changeLang:
    path: /changelang
    defaults: { _controller: StoreBundle:Main:changeLang }

store_stores_loc:
    path: /stores
    defaults: { _controller: StoreBundle:Stores:stores }

admin_login:
    path: /admin
    defaults: { _controller: StoreBundle:Security:adminLogin }

admin_control_panel:
    path: /admin/cpanel
    defaults: { _controller: StoreBundle:Admin:cpanel}

user_registration:
    path:     /register
    defaults: { _controller: StoreBundle:Registration:register }

admin_registration:
    path: /regadmin
    defaults: { _controller: StoreBundle:Registration:regAdmin }
store_user:
    path: /user
    defaults: { _controller: StoreBundle:User:index }

user_logout:
    path: /logout

admin_logout:
    path: /admin/cpanel/logout

currency:
    path: /admin/cpanel/currency
    defaults: { _controller: StoreBundle:Admin:settingsCurrency }

add_new_currency:
    path: /admin/cpanel/addnewcurrency
    defaults: { _controller: StoreBundle:Admin:addNewCurrency }

delete_currency:
    path: /admin/cpanel/deletecurrency
    defaults: { _controller: StoreBundle:Admin:deleteCurrency }

update_currency:
    path: admin/cpanel/updatecurrency
    defaults: { _controller: StoreBundle:Admin:updateCurrency }