# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        entity_admin:
            class: StoreBundle\Entity\Admin
            algorithm: bcrypt
        entity_user:
            class: StoreBundle\Entity\User
            algorithm: bcrypt

    providers:
        admin_provider:
            entity:
               class: StoreBundle:Admin
               property: username
        user_provider:
            entity:
              class: StoreBundle:User
              property: username

        in_memory:
            memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            pattern: ^/admin
            http_basic: ~
            provider: admin_provider
            anonymous: ~
            form_login:
                login_path: admin_login
                check_path: admin_login
            logout:
                path: /admin/cpanel/logout
                target: /admin
        main:
            pattern: ^/
            http_basic: ~
            provider: user_provider
            anonymous: ~
            form_login:
                login_path: store_login
                check_path: store_login
            logout:
                path:   /logout
                target: /

            logout:
                path: /logout
                target: /

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /admin/cpanel, roles: ROLE_ADMIN }
        - { path: ^/user, roles: ROLE_USER }